# rabiitmq配置
spring:
    rabbitmq:
       host: 123.206.111.215
       port: 5672
       username: yiranadmin
       password: yiran123456
       publisher-confirms: true
       publisher-returns: true
